server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.ccfish.springcloud.entity
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
  
spring:
  application:
    name: microservicecloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/clouddb02
    username: root
    password: 123456
    dbcp2: 
      min-idle: 5
      initial-size: 5
      max-total: 5

eureka:
  client:
    service-url:
      # 单机 defaultZone: http://localhost:7001/eureka/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002 #注册进eureka的名字
    prefer-ip-address: true #显示ip提示
info:
  app.name: ccfish-microservicecloud
  company.name: www.qqhapi.com
  build.artifactId: microservicecloud-provider-dept-8002 #pom中build配置，读取pom内容
  build.version: 0.0.1-SNAPSHOT